framework:
  - all

directory:
  - common-resources

skip-check:
  - CKV_AWS_18 # No need for access logging
  - CKV2_AWS_42 # Assign a custom Domain costs money
  - CKV2_AWS_62 # No need for event notifications in this case
  - CKV_AWS_144 # No need for cross region replication
