name: CI - Terraform Dev Only

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch: 

jobs:
  terraform-dev-checks:
    name: Dev Terraform / Lint / Checkov
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Install Terragrunt
        run: |
          curl -sL https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init

      - name: Install Checkov
        run: |
          pip install checkov==3.2.410

      - name: Terraform Format Check
        working-directory: envs/dev/front
        run: terraform fmt -check -recursive

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHubActionsSession
          aws-region: us-east-1

      - name: Terraform Validate
        working-directory: envs/dev/front
        run: terragrunt validate

      - name: TFLint
        working-directory: envs/dev/front
        run: tflint --recursive

      - name: Terraform Init
        working-directory: envs/dev/front
        run: terragrunt init -input=false
      
      - name: Terraform Plan
        working-directory: envs/dev/front
        run: terragrunt plan -input=false

      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          echo "$HOME/.infracost/bin" >> $GITHUB_PATH

      - name: Setup Infracost API key
        run: |
          echo "INFRACOST_API_KEY=${{ secrets.INFRACOST_API_KEY }}" >> $GITHUB_ENV

      - name: Generate Terraform plan JSON
        working-directory: envs/dev/front
        run: |
          terragrunt plan -input=false -out=tfplan.binary
          terragrunt show -json tfplan.binary > plan.json

      - name: Generate Infracost breakdown
        working-directory: envs/dev/front
        run: |
          infracost breakdown --path plan.json --format json --out-file infracost-out.json

      - name: Output Infracost cost estimate
        run: |
          infracost output --path envs/dev/front/infracost-out.json --format table
